version: "3.8"

services:
  # 🗄️ SQL Server - PROD
  gescomph-sqlserver-prod:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gescomph-sqlserver-prod
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin123"
      MSSQL_PID: "Developer"
    ports:
      - "1435:1433"
    volumes:
      - sqldata_prod:/var/opt/mssql
    networks:
      - network_prod

  # 🌐 API principal - PROD
  gescomph-api-prod:
    container_name: gescomph-api-prod
    build:
      context: ../..
      dockerfile: WebGESCOMPH/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - gescomph-postgres-prod
    ports:
      - "5103:8080"
    networks:
      - network_prod
    labels:
      - com.gescomph.environment=prod

volumes:
  pgdata_prod:

networks:
  network_prod:
    driver: bridge
