version: "3.8"

services:
  # 🌐 API principal - PROD
  gescomph-api-prod:
    container_name: gescomph-api-prod
    build:
      context: ../..
      dockerfile: WebGESCOMPH/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      gescomph-sqlserver-prod:
        condition: service_healthy
    ports:
      - "5103:8080"
    networks:
      - network_prod
    labels:
      - com.gescomph.environment=prod

volumes:
  sqldata_prod:

networks:
  network_prod:
    driver: bridge
