version: '3.8'

services:
  # 🌐 API principal - QA
  gescomph-api-qa:
    container_name: gescomph-api-qa
    build:
      context: ../..
      dockerfile: WebGESCOMPH/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      gescomph-sqlserver-qa:
        condition: service_healthy
    ports:
      - "5101:8080"
    networks:
      - network_qa
    labels:
      - com.gescomph.environment=qa

volumes:
  sqldata_qa:

networks:
  network_qa:
    driver: bridge
