version: '3.8'

services:
  # 🗄️ SQL Server - QA
  gescomph-sqlserver-qa:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gescomph-sqlserver-qa
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin123"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"      # Puerto externo diferente para QA
    volumes:
      - sqldata_qa:/var/opt/mssql
    networks:
      - network_qa
  # 🌐 API principal - QA
  gescomph-api-qa:
    container_name: gescomph-api-qa
    build:
      context: ../..
      dockerfile: WebGESCOMPH/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - gescomph-postgres-qa
    ports:
      - "5101:8080"
    networks:
      - network_qa
    labels:
      - com.gescomph.environment=qa

volumes:
  pgdata_qa:

networks:
  network_qa:
    driver: bridge
