//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments1
    {
        public int Id { get; set; }
        public bool Active { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Description { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<System.DateTime> DateTimeAssigned { get; set; }
        public string Observation { get; set; }
        public int PersonId { get; set; }
        public int EstablishmentId { get; set; }
    
        public virtual Establishments1 Establishments { get; set; }
        public virtual Persons1 Persons { get; set; }
    }
}
