//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATABASECHANGELOG
    {
        public string ID { get; set; }
        public string AUTHOR { get; set; }
        public string FILENAME { get; set; }
        public System.DateTime DATEEXECUTED { get; set; }
        public int ORDEREXECUTED { get; set; }
        public string EXECTYPE { get; set; }
        public string MD5SUM { get; set; }
        public string DESCRIPTION { get; set; }
        public string COMMENTS { get; set; }
        public string TAG { get; set; }
        public string LIQUIBASE { get; set; }
        public string CONTEXTS { get; set; }
        public string LABELS { get; set; }
        public string DEPLOYMENT_ID { get; set; }
    }
}
