//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Establishments1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Establishments1()
        {
            this.Appointments = new HashSet<Appointments1>();
            this.PremisesLeaseds = new HashSet<PremisesLeaseds1>();
        }
    
        public int Id { get; set; }
        public bool Active { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal AreaM2 { get; set; }
        public decimal RentValueBase { get; set; }
        public string Address { get; set; }
        public decimal UvtQty { get; set; }
        public int PlazaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointments1> Appointments { get; set; }
        public virtual Plazas Plazas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PremisesLeaseds1> PremisesLeaseds { get; set; }
    }
}
