//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObligationMonths1
    {
        public int Id { get; set; }
        public bool Active { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int ContractId { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public decimal UvtQtyApplied { get; set; }
        public decimal UvtValueApplied { get; set; }
        public decimal VatRateApplied { get; set; }
        public decimal BaseAmount { get; set; }
        public decimal VatAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<int> DaysLate { get; set; }
        public Nullable<decimal> LateAmount { get; set; }
        public int Status { get; set; }
        public bool Locked { get; set; }
        public Nullable<decimal> LateFeeAmount { get; set; }
        public Nullable<System.DateTime> NotifiedDueSoonAt { get; set; }
        public Nullable<System.DateTime> NotifiedOverdueAt { get; set; }
        public Nullable<System.DateTime> NotifiedPreJudicialAt { get; set; }
        public Nullable<System.DateTime> NotifiedJudicialAt { get; set; }
    
        public virtual Contracts1 Contracts { get; set; }
    }
}
