//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwoFactorCodes
    {
        public int Id { get; set; }
        public bool Active { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int UserId { get; set; }
        public string Code { get; set; }
        public System.DateTime ExpiresAt { get; set; }
        public bool IsUsed { get; set; }
        public Nullable<System.DateTime> UsedAt { get; set; }
    
        public virtual Users1 Users { get; set; }
    }
}
